name: Auto-approve Renovate patch PRs

on:
  workflow_call:

jobs:
  approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: >
      github.event.pull_request.user.login == 'renovate[bot]' &&
      contains(github.event.pull_request.labels.*.name, 'renovate/patch')
    steps:
      - name: Approve PR
        run: gh pr review "${{ github.event.pull_request.number }}" --approve --repo "${{ github.repository }}"
        env:
          GH_TOKEN: ${{ github.token }}
